apiVersion: v1
kind: Service
metadata:
  name: apps-web
  labels:
    app: apps-web
spec:
  clusterIP: None
  selector:
    app: apps-web
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-web
  labels:
    app: apps-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-web
  template:
    metadata:
      labels:
        app: apps-web
    spec:
      containers:
        - name: apps-web
          image: apps-web
