apiVersion: v1
kind: Service
metadata:
  name: apps-web
  labels:
    app: apps-web
spec:
  clusterIP: None
  selector:
    app: apps-web
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-web
  labels:
    app: apps-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-web
  template:
    metadata:
      labels:
        app: apps-web
    spec:
      containers:
        - name: apps-web
          image: apps-web
          volumeMounts:
            - name: source-volume
              mountPath: /app/apps/web
            - name: yarn-cache-volume
              mountPath: /app/.yarn
            - name: pnp-map-volume
              mountPath: /app/.pnp.cjs
      volumes:
        - name: source-volume
          hostPath:
            path: /apps/web
            type: Directory
        - name: yarn-cache-volume
          hostPath:
            path: /.yarn
            type: Directory
        - name: pnp-map-volume
          hostPath:
            path: /.pnp.cjs
            type: File
