FROM mhart/alpine-node:16.4.2

WORKDIR /app

# copy our repo level configs, yarn package cache, etc
COPY .pnp.cjs .pnp.loader.mjs .yarnrc.yml package.json tsconfig.json yarn.lock ./

# copy our potential local dependencies
COPY packages/ ./packages

# copy our app
COPY apps/web/ ./apps/web

EXPOSE 8080

CMD ["yarn", "workspace", "@bleh/web", "start"]
