FROM mhart/alpine-node:16.4.2

WORKDIR /app

# copy our repo level configs, yarn package cache, etc
COPY .pnp.cjs .pnp.loader.mjs .yarnrc.yml package.json tsconfig.json yarn.lock ./

# copy our potential local dependencies
COPY packages/ ./packages

# copy our service
COPY services/graphql-gateway/ ./services/graphql-gateway

EXPOSE 3000

CMD ["yarn", "workspace", "@bleh/graphql-gateway", "start"]
